version: '3.8'

services: 

  postgres: 
    container_name: pg
    image: postgres:16
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./config/postgresql.conf:/etc/postgresql.conf
      - /srv/docker/postgresql:/var/lib/postgresql   
      - ./database:/var/lib/postgresql 